# Generated by Django 3.0 on 2019-12-22 01:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0007_list_shared_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='deadline',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
