# Generated by Django 3.0 on 2019-12-22 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0008_item_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_finish',
            field=models.BooleanField(default=False),
        ),
    ]
