# Generated by Django 3.0 on 2019-12-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0009_item_is_finish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='deadline',
            field=models.DateField(default='2019-12-24'),
        ),
    ]
