# Generated by Django 3.0 on 2019-12-23 07:58

import datetime
from django.db import migrations, models
from django.utils import timezone
from datetime import timedelta

class Migration(migrations.Migration):

    tommorow = timezone.now() + datetime.timedelta(1)
    dependencies = [
        ('lists', '0010_auto_20191223_0447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='deadline',
            field=models.DateField(default=tommorow),
        ),
    ]
